- name: Install python3
  yum:
    name: python3
    state: latest
    update_cache: yes

- name: Set timezone to Europe/Moscow
  community.general.timezone:
    name: Europe/Moscow

- name: Install fail2ban
  yum:
    name: fail2ban
    state: latest
    update_cache: yes

- name: Install ntp
  yum:
    name: ntp
    state: latest
    update_cache: yes

- name: ensure grub params
  lineinfile:
    path: /etc/default/grub
    line: "{{ item }}"
  with_items:
    - GRUB_CMDLINE_LINUX="ipv6.disable=1"
    - GRUB_CMDLINE_LINUX="audit=1"
    - GRUB_CMDLINE_LINUX="audit_backlog_limit=8192"
  notify: update-c7-grub

- name: set up signature verification for packages
  lineinfile:
    path: "{{ item }}"
    regexp: "^gpgcheck="
    line: "gpgcheck=1"
  with_items:
    - /etc/yum.conf
  failed_when: false

- name: delete old unsecure progs
  yum:
    name: "{{ progs_to_delete }}"
    state: absent